-- HRMS PostgreSQL Schema Definition
-- Schema: hrms

CREATE SCHEMA IF NOT EXISTS hrms AUTHORIZATION postgres;

CREATE TYPE hrms."approval_document_type_enum" AS ENUM (
	'ATTENDANCE_ADJUSTMENT',
	'LEAVE_REQUEST',
	'RESIGNATION_REQUEST',
	'CERTIFICATE_REQUEST',
	'EMPLOYMENT_CONTRACT',
	'PAYROLL_PERIOD');

-- Master Data Tables
CREATE TABLE hrms.bank (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	bank_code varchar(50) NOT NULL UNIQUE,
	bank_name varchar(255) NOT NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE hrms.certificate_type (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	certificate_code varchar(50) NOT NULL UNIQUE,
	certificate_name varchar(255) NOT NULL
);

CREATE TABLE hrms.company (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_code varchar(50) NOT NULL UNIQUE,
	company_name varchar(255) NOT NULL,
	address text NULL,
	phone varchar(50) NULL,
	email varchar(255) NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	logo_data bytea NULL
);

CREATE TABLE hrms.document_type (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	document_code varchar(50) NOT NULL UNIQUE,
	document_name varchar(255) NOT NULL,
	requires_expiry bool DEFAULT false NOT NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE hrms.employee_type (
	id bigserial PRIMARY KEY,
	type_code varchar(20) NOT NULL UNIQUE,
	type_name varchar(100) NOT NULL,
	wage_type varchar(20) NOT NULL,
	has_social_security bool DEFAULT true NOT NULL,
	has_leave_entitlement bool DEFAULT true NOT NULL,
	has_overtime bool DEFAULT true NOT NULL,
	has_provident_fund bool DEFAULT false NOT NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE hrms.gender_type (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	gender_code varchar(20) NOT NULL UNIQUE,
	gender_name varchar(50) NOT NULL
);

CREATE TABLE hrms.leave_type (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	leave_code varchar(50) NOT NULL UNIQUE,
	leave_name varchar(255) NOT NULL,
	unit varchar(20) DEFAULT 'DAY' NOT NULL CHECK (unit IN ('DAY', 'HOUR')),
	paid bool DEFAULT false NOT NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE hrms.marital_status_type (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	marital_status_name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE hrms.nationality (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nationality_name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE hrms.religion (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	religion_name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE hrms."permission" (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	permission_code varchar(100) NOT NULL UNIQUE,
	permission_name varchar(255) NOT NULL,
	description text NULL
);

CREATE TABLE hrms."role" (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	role_code varchar(50) NOT NULL UNIQUE,
	role_name varchar(150) NOT NULL,
	description text NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE hrms.role_permission (
	role_id int8 NOT NULL REFERENCES hrms."role"(id) ON DELETE CASCADE,
	permission_id int8 NOT NULL REFERENCES hrms."permission"(id) ON DELETE CASCADE,
	PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE hrms.role_data_scope (
	role_id int8 NOT NULL REFERENCES hrms."role"(id) ON DELETE CASCADE,
	permission_id int8 NOT NULL REFERENCES hrms."permission"(id) ON DELETE CASCADE,
	scope_type varchar(30) NOT NULL CHECK (scope_type IN ('SELF', 'TEAM', 'DEPARTMENT', 'DIVISION', 'ORGANIZATION')),
	PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE hrms.shift (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	shift_code varchar(50) NOT NULL UNIQUE,
	shift_name varchar(255) NOT NULL,
	start_time time NOT NULL,
	end_time time NOT NULL,
	cross_day bool DEFAULT false NOT NULL,
	break_minutes int4 DEFAULT 0 NOT NULL CHECK (break_minutes >= 0),
	late_grace_minutes int4 DEFAULT 0 NOT NULL CHECK (late_grace_minutes >= 0),
	early_leave_grace_minutes int4 DEFAULT 0 NOT NULL CHECK (early_leave_grace_minutes >= 0),
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE hrms.work_schedule (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	schedule_code varchar(50) NOT NULL UNIQUE,
	schedule_name varchar(255) NOT NULL,
	work_start time NULL,
	work_end time NULL,
	break_minutes int4 DEFAULT 0 NOT NULL CHECK (break_minutes >= 0),
	late_grace_minutes int4 DEFAULT 0 NOT NULL CHECK (late_grace_minutes >= 0),
	early_leave_grace_minutes int4 DEFAULT 0 NOT NULL CHECK (early_leave_grace_minutes >= 0),
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE hrms.work_week (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_id int8 NOT NULL REFERENCES hrms.company(id),
	day_of_week int2 NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
	is_working_day bool DEFAULT true NOT NULL,
	UNIQUE (company_id, day_of_week)
);

CREATE TABLE hrms.holiday (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	holiday_date date NOT NULL,
	holiday_name varchar(255) NOT NULL,
	company_id int8 NOT NULL REFERENCES hrms.company(id),
	holiday_type varchar(50) DEFAULT 'PUBLIC' NOT NULL,
	UNIQUE (company_id, holiday_date)
);

CREATE TABLE hrms.company_bank_account (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_id int8 NOT NULL REFERENCES hrms.company(id),
	bank_id int8 NOT NULL REFERENCES hrms.bank(id),
	account_number varchar(100) NOT NULL,
	account_name varchar(255) NULL,
	is_primary bool DEFAULT false NOT NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE hrms.employee_level (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	level_code varchar(50) NOT NULL UNIQUE,
	level_name varchar(100) NOT NULL,
	level_rank int4 NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
	min_salary numeric(15, 2) DEFAULT 0 NULL,
	max_salary numeric(15, 2) DEFAULT 0 NULL,
	approval_limit numeric(15, 2) DEFAULT 0 NULL,
	default_flow_id int8 NULL
);

-- Employee & Organization Core
CREATE TABLE hrms.employee (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_code varchar(50) NOT NULL UNIQUE,
	prefix varchar(50) NULL,
	first_name varchar(150) NOT NULL,
	last_name varchar(150) NOT NULL,
	citizen_id varchar(30) NULL,
	citizen_id_encrypted bytea NULL,
	citizen_id_masked varchar(20) NULL,
	birth_date date NULL,
	gender varchar(30) NULL,
	gender_id int8 NULL REFERENCES hrms.gender_type(id),
	nationality varchar(100) NULL,
	nationality_id int8 NULL REFERENCES hrms.nationality(id),
	religion varchar(100) NULL,
	religion_id int8 NULL REFERENCES hrms.religion(id),
	marital_status varchar(30) NULL,
	marital_status_id int8 NULL REFERENCES hrms.marital_status_type(id),
	military_status varchar(50) NULL,
	is_top_level bool DEFAULT false NOT NULL,
	spouse_has_income bool DEFAULT false NOT NULL,
	number_of_children int4 DEFAULT 0 NOT NULL,
	parent_deduction_count int4 DEFAULT 0 NOT NULL,
	disability_deduction_count int4 DEFAULT 0 NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE hrms.user_account (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL UNIQUE REFERENCES hrms.employee(id),
	username varchar(100) NOT NULL UNIQUE,
	password_hash text NOT NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED')),
	last_login_at timestamptz NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE hrms.user_role (
	user_id int8 NOT NULL REFERENCES hrms.user_account(id) ON DELETE CASCADE,
	role_id int8 NOT NULL REFERENCES hrms."role"(id) ON DELETE CASCADE,
	PRIMARY KEY (user_id, role_id)
);

CREATE TABLE hrms.division (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_id int8 NOT NULL REFERENCES hrms.company(id),
	division_code varchar(50) NOT NULL,
	division_name varchar(255) NOT NULL,
	head_employee_id int8 NULL REFERENCES hrms.employee(id),
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	UNIQUE (company_id, division_code)
);

CREATE TABLE hrms.department (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	division_id int8 NOT NULL REFERENCES hrms.division(id),
	parent_department_id int8 NULL REFERENCES hrms.department(id),
	department_code varchar(50) NOT NULL,
	department_name varchar(255) NOT NULL,
	head_employee_id int8 NULL REFERENCES hrms.employee(id),
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	UNIQUE (division_id, department_code)
);

CREATE TABLE hrms."position" (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	department_id int8 NOT NULL REFERENCES hrms.department(id),
	level_id int8 NULL REFERENCES hrms.employee_level(id),
	position_code varchar(50) NOT NULL UNIQUE,
	position_name varchar(255) NOT NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL
);

-- Employee Details
CREATE TABLE hrms.employee_address (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id) ON DELETE CASCADE,
	address_type varchar(30) NOT NULL CHECK (address_type IN ('REGISTERED', 'CURRENT', 'OTHER')),
	address_line text NULL,
	sub_district varchar(150) NULL,
	district varchar(150) NULL,
	province varchar(150) NULL,
	postal_code varchar(20) NULL,
	is_current bool DEFAULT true NOT NULL
);

CREATE TABLE hrms.employee_contact (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL UNIQUE REFERENCES hrms.employee(id) ON DELETE CASCADE,
	personal_phone varchar(50) NULL,
	personal_email varchar(255) NULL,
	organization_email varchar(255) NULL
);

CREATE TABLE hrms.emergency_contact (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id) ON DELETE CASCADE,
	first_name varchar(150) NOT NULL,
	last_name varchar(150) NOT NULL,
	relationship varchar(100) NULL,
	primary_phone varchar(50) NOT NULL,
	secondary_phone varchar(50) NULL,
	address text NULL,
	is_primary bool DEFAULT false NOT NULL
);

CREATE TABLE hrms.family_member (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id) ON DELETE CASCADE,
	relationship_type varchar(30) NOT NULL,
	first_name varchar(150) NOT NULL,
	last_name varchar(150) NULL,
	citizen_id varchar(30) NULL,
	citizen_id_encrypted bytea NULL,
	citizen_id_masked varchar(20) NULL,
	birth_date date NULL,
	marital_status varchar(30) NULL,
	education_status varchar(100) NULL
);

CREATE TABLE hrms.employee_education (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id) ON DELETE CASCADE,
	education_level varchar(100) NOT NULL,
	institution varchar(255) NOT NULL,
	major varchar(255) NULL,
	graduation_year int4 NULL,
	gpa numeric(4, 2) NULL CHECK (gpa IS NULL OR (gpa >= 0 AND gpa <= 4))
);

CREATE TABLE hrms.employee_work_experience (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id) ON DELETE CASCADE,
	company_name varchar(255) NOT NULL,
	position_name varchar(255) NULL,
	start_date date NULL,
	end_date date NULL,
	last_salary numeric(15, 2) NULL CHECK (last_salary IS NULL OR last_salary >= 0),
	leaving_reason text NULL,
	CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE TABLE hrms.employee_bank_account (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id) ON DELETE CASCADE,
	bank_id int8 NOT NULL REFERENCES hrms.bank(id),
	account_number varchar(100) NOT NULL,
	account_type varchar(50) NULL,
	account_name varchar(255) NULL,
	is_primary bool DEFAULT false NOT NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
	UNIQUE (bank_id, account_number)
);

CREATE TABLE hrms.employee_social_security (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL UNIQUE REFERENCES hrms.employee(id) ON DELETE CASCADE,
	social_security_no varchar(50) NULL,
	social_security_no_encrypted bytea NULL,
	social_security_no_masked varchar(20) NULL,
	hospital_name varchar(255) NULL,
	hospital_code varchar(50) NULL
);

CREATE TABLE hrms.employee_document (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id) ON DELETE CASCADE,
	document_type_id int8 NOT NULL REFERENCES hrms.document_type(id),
	file_name varchar(255) NULL,
	file_data bytea NULL,
	issued_date date NULL,
	expiry_date date NULL,
	uploaded_at timestamptz DEFAULT now() NOT NULL,
	uploaded_by_employee_id int8 NULL REFERENCES hrms.employee(id),
	CHECK (expiry_date IS NULL OR issued_date IS NULL OR expiry_date >= issued_date)
);

-- Approval Engine
CREATE TABLE hrms.approval_flow (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	flow_code varchar(50) NOT NULL UNIQUE,
	flow_name varchar(255) NOT NULL,
	document_type hrms."approval_document_type_enum" NOT NULL,
	department_id int8 NULL REFERENCES hrms.department(id),
	level_id int8 NULL REFERENCES hrms.employee_level(id),
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
	created_at timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE hrms.approval_step (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	flow_id int8 NOT NULL REFERENCES hrms.approval_flow(id) ON DELETE CASCADE,
	step_no int4 NOT NULL,
	approver_type varchar(30) NOT NULL CHECK (approver_type IN ('EMPLOYEE', 'ROLE', 'MANAGER', 'DEPARTMENT_HEAD', 'DIVISION_HEAD', 'HR', 'CEO')),
	approver_employee_id int8 NULL REFERENCES hrms.employee(id),
	approver_role_id int8 NULL REFERENCES hrms."role"(id),
	is_required bool DEFAULT true NOT NULL,
	UNIQUE (flow_id, step_no)
);

CREATE TABLE hrms.approval_instance (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	flow_id int8 NOT NULL REFERENCES hrms.approval_flow(id),
	document_type hrms."approval_document_type_enum" NOT NULL,
	document_id int8 NOT NULL,
	current_step_no int4 NULL,
	status varchar(30) DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
	created_at timestamptz DEFAULT now() NOT NULL,
	completed_at timestamptz NULL
);

CREATE TABLE hrms.approval_delegation (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	delegator_employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	delegate_employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	document_type varchar(50) NULL,
	start_date date NOT NULL,
	end_date date NOT NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
	CHECK (end_date >= start_date),
	CHECK (delegator_employee_id <> delegate_employee_id)
);

CREATE TABLE hrms.approval_action (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	approval_instance_id int8 NOT NULL REFERENCES hrms.approval_instance(id) ON DELETE CASCADE,
	step_id int8 NULL REFERENCES hrms.approval_step(id),
	approver_employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	"action" varchar(30) NOT NULL CHECK (action IN ('APPROVE', 'REJECT', 'RETURN', 'CANCEL')),
	"comment" text NULL,
	action_at timestamptz DEFAULT now() NOT NULL,
	delegation_id int8 NULL REFERENCES hrms.approval_delegation(id),
	acted_for_employee_id int8 NULL REFERENCES hrms.employee(id),
	signature_data bytea NULL
);

-- Contracts & Assignments
CREATE TABLE hrms.employment_contract (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	employee_type_id int8 NULL REFERENCES hrms.employee_type(id),
	contract_type varchar(30) NOT NULL CHECK (contract_type IN ('PROBATION', 'PERMANENT', 'FIXED_TERM', 'OTHER')),
	wage_type varchar(20) NULL CHECK (wage_type IS NULL OR wage_type IN ('DAILY', 'MONTHLY')),
	start_date date NOT NULL,
	probation_end_date date NULL,
	probation_passed_date date NULL,
	contract_end_date date NULL,
	termination_date date NULL,
	termination_reason text NULL,
	status varchar(30) DEFAULT 'PENDING_APPROVAL' NOT NULL CHECK (status IN ('PENDING_APPROVAL', 'ACTIVE', 'COMPLETED', 'TERMINATED', 'CANCELLED')),
	approval_instance_id int8 NULL REFERENCES hrms.approval_instance(id),
	CHECK (contract_end_date IS NULL OR contract_end_date >= start_date),
	CHECK (termination_date IS NULL OR termination_date >= start_date)
);

CREATE TABLE hrms.employee_status_history (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	source_contract_id int8 NULL REFERENCES hrms.employment_contract(id),
	status varchar(30) NOT NULL CHECK (status IN ('PROBATION', 'PERMANENT', 'FIXED_TERM', 'RESIGNED', 'TERMINATED', 'OTHER')),
	effective_from date NOT NULL,
	effective_to date NULL,
	reason text NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE TABLE hrms.employee_assignment (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	division_id int8 NOT NULL REFERENCES hrms.division(id),
	department_id int8 NOT NULL REFERENCES hrms.department(id),
	position_id int8 NOT NULL REFERENCES hrms."position"(id),
	level_id int8 NULL REFERENCES hrms.employee_level(id),
	employee_type_id int8 NULL REFERENCES hrms.employee_type(id),
	work_schedule_id int8 NULL REFERENCES hrms.work_schedule(id),
	manager_employee_id int8 NULL REFERENCES hrms.employee(id),
	effective_from date NOT NULL,
	effective_to date NULL,
	is_current bool DEFAULT true NOT NULL,
	wage_type varchar(20) DEFAULT 'MONTHLY' NOT NULL CHECK (wage_type IN ('DAILY', 'MONTHLY')),
	CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

-- Attendance
CREATE TABLE hrms.employee_shift (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	shift_id int8 NOT NULL REFERENCES hrms.shift(id),
	effective_from date NOT NULL,
	effective_to date NULL,
	CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE TABLE hrms.attendance_daily (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	work_date date NOT NULL,
	shift_id int8 NULL REFERENCES hrms.shift(id),
	work_schedule_id int8 NULL REFERENCES hrms.work_schedule(id),
	scheduled_start timestamptz NULL,
	scheduled_end timestamptz NULL,
	actual_in timestamptz NULL,
	actual_out timestamptz NULL,
	worked_minutes int4 DEFAULT 0 NOT NULL CHECK (worked_minutes >= 0),
	late_minutes int4 DEFAULT 0 NOT NULL CHECK (late_minutes >= 0),
	early_leave_minutes int4 DEFAULT 0 NOT NULL CHECK (early_leave_minutes >= 0),
	"absent" bool DEFAULT false NOT NULL,
	status varchar(30) DEFAULT 'PRESENT' NOT NULL,
	UNIQUE (employee_id, work_date),
	CHECK (NOT (shift_id IS NOT NULL AND work_schedule_id IS NOT NULL))
);

CREATE TABLE hrms.attendance_import_batch (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	file_name varchar(255) NULL,
	file_hash varchar(64) NULL,
	file_data bytea NULL,
	"source" varchar(50) NULL,
	device_name varchar(100) NULL,
	unit_name varchar(100) NULL,
	date_from date NULL,
	date_to date NULL,
	exported_at timestamptz NULL,
	imported_by_user_id int8 NULL REFERENCES hrms.user_account(id),
	imported_at timestamptz DEFAULT now() NOT NULL,
	total_records int4 DEFAULT 0 NULL,
	success_records int4 DEFAULT 0 NULL,
	failed_records int4 DEFAULT 0 NULL,
	status varchar(20) DEFAULT 'IMPORTED' NOT NULL CHECK (status IN ('IMPORTED', 'PARTIAL', 'FAILED'))
);

CREATE TABLE hrms.attendance_import_error (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	import_batch_id int8 NOT NULL REFERENCES hrms.attendance_import_batch(id) ON DELETE CASCADE,
	"row_number" int4 NOT NULL,
	raw_row_data jsonb NOT NULL,
	error_message text NOT NULL,
	error_code varchar(50) NULL,
	employee_code varchar(50) NULL,
	employee_name varchar(255) NULL,
	department_name varchar(100) NULL,
	punch_time_raw varchar(50) NULL,
	machine_state varchar(50) NULL,
	created_at timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE hrms.attendance_adjustment (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	attendance_id int8 NOT NULL REFERENCES hrms.attendance_daily(id),
	requested_by_employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	old_in timestamptz NULL,
	old_out timestamptz NULL,
	new_in timestamptz NULL,
	new_out timestamptz NULL,
	reason text NOT NULL,
	status varchar(30) DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
	approval_instance_id int8 NULL REFERENCES hrms.approval_instance(id),
	created_at timestamptz DEFAULT now() NOT NULL,
	reviewed_at timestamptz NULL,
	reviewed_by_employee_id int8 NULL REFERENCES hrms.employee(id)
);

CREATE TABLE hrms.attendance_monthly_summary (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	"year" int4 NOT NULL,
	"month" int4 NOT NULL CHECK (month >= 1 AND month <= 12),
	total_work_days int4 DEFAULT 0 NOT NULL,
	total_worked_minutes int4 DEFAULT 0 NOT NULL,
	total_late_minutes int4 DEFAULT 0 NOT NULL,
	total_early_leave_minutes int4 DEFAULT 0 NOT NULL,
	total_absent_days int4 DEFAULT 0 NOT NULL,
	generated_at timestamptz DEFAULT now() NOT NULL,
	UNIQUE (employee_id, year, month)
);

-- Leave
CREATE TABLE hrms.leave_policy (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	leave_type_id int8 NOT NULL REFERENCES hrms.leave_type(id),
	employee_type_id int8 NULL REFERENCES hrms.employee_type(id),
	employee_level_id int8 NULL REFERENCES hrms.employee_level(id) ON DELETE SET NULL,
	entitlement_days numeric(8, 2) DEFAULT 0 NOT NULL CHECK (entitlement_days >= 0),
	minimum_service_days int4 DEFAULT 0 NOT NULL CHECK (minimum_service_days >= 0),
	advance_request_days int4 DEFAULT 0 NOT NULL CHECK (advance_request_days >= 0),
	carry_forward_allowed bool DEFAULT false NOT NULL,
	carry_forward_max_months int4 NULL,
	carry_forward_expiry_months int4 NULL,
	document_required bool DEFAULT false NOT NULL,
	document_required_after_days numeric(8, 2) NULL,
	allow_during_probation bool DEFAULT false NOT NULL,
	effective_from date NOT NULL,
	effective_to date NULL,
	max_lifetime_occurrences int4 NULL,
	max_days_per_occurrence numeric(8, 2) NULL,
	max_occurrences_per_year int4 NULL,
	UNIQUE (leave_type_id, employee_type_id),
	CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE TABLE hrms.leave_balance (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	leave_type_id int8 NOT NULL REFERENCES hrms.leave_type(id),
	"year" int4 NOT NULL,
	opening_balance numeric(8, 2) DEFAULT 0 NOT NULL,
	entitlement numeric(8, 2) DEFAULT 0 NOT NULL,
	carried_forward numeric(8, 2) DEFAULT 0 NOT NULL,
	used_days numeric(8, 2) DEFAULT 0 NOT NULL,
	adjusted_days numeric(8, 2) DEFAULT 0 NOT NULL,
	remaining_days numeric(8, 2) DEFAULT 0 NOT NULL,
	carry_forward_expiry date NULL,
	UNIQUE (employee_id, leave_type_id, year)
);

CREATE TABLE hrms.leave_balance_transaction (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	balance_id int8 NOT NULL REFERENCES hrms.leave_balance(id),
	transaction_type varchar(30) NOT NULL CHECK (transaction_type IN ('OPENING', 'ENTITLEMENT', 'CARRY_FORWARD', 'USED', 'ADJUSTMENT', 'EXPIRED', 'REVERSAL')),
	amount numeric(8, 2) NOT NULL,
	reference_type varchar(50) NULL,
	reference_id int8 NULL,
	note text NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	created_by_employee_id int8 NULL REFERENCES hrms.employee(id)
);

CREATE TABLE hrms.leave_request (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	request_no varchar(50) NOT NULL UNIQUE,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	leave_type_id int8 NOT NULL REFERENCES hrms.leave_type(id),
	start_datetime timestamptz NOT NULL,
	end_datetime timestamptz NOT NULL,
	leave_hours numeric(8, 2) DEFAULT 0 NOT NULL CHECK (leave_hours >= 0),
	leave_days numeric(8, 2) DEFAULT 0 NOT NULL CHECK (leave_days >= 0),
	reason text NULL,
	status varchar(30) DEFAULT 'DRAFT' NOT NULL CHECK (status IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
	submitted_at timestamptz NULL,
	cancelled_at timestamptz NULL,
	cancel_reason text NULL,
	CHECK (end_datetime >= start_datetime)
);

CREATE TABLE hrms.leave_request_document (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	request_id int8 NOT NULL REFERENCES hrms.leave_request(id) ON DELETE CASCADE,
	file_name varchar(255) NULL,
	file_data bytea NULL,
	uploaded_at timestamptz DEFAULT now() NOT NULL
);

-- Compensation & Payroll
CREATE TABLE hrms.salary_structure (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	position_id int8 NULL REFERENCES hrms."position"(id),
	level_id int8 NULL REFERENCES hrms.employee_level(id),
	min_salary numeric(15, 2) DEFAULT 0 NOT NULL CHECK (min_salary >= 0),
	max_salary numeric(15, 2) DEFAULT 0 NOT NULL,
	default_salary numeric(15, 2) NULL,
	effective_from date NOT NULL,
	effective_to date NULL,
	CHECK (max_salary >= min_salary),
	CHECK (default_salary IS NULL OR (default_salary >= min_salary AND default_salary <= max_salary)),
	CHECK (effective_to IS NULL OR effective_to >= effective_from),
	CHECK (position_id IS NOT NULL OR level_id IS NOT NULL)
);

CREATE TABLE hrms.employee_salary (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	base_salary numeric(15, 2) NOT NULL CHECK (base_salary >= 0),
	effective_from date NOT NULL,
	effective_to date NULL,
	reason text NULL,
	approved_by_employee_id int8 NULL REFERENCES hrms.employee(id),
	created_at timestamptz DEFAULT now() NOT NULL,
	CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE TABLE hrms.payroll_item (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	item_code varchar(50) NOT NULL UNIQUE,
	item_name varchar(255) NOT NULL,
	item_type varchar(20) NOT NULL CHECK (item_type IN ('EARNING', 'DEDUCTION')),
	calculation_type varchar(30) NOT NULL CHECK (calculation_type IN ('FIXED', 'FORMULA', 'MANUAL', 'IMPORT')),
	taxable bool DEFAULT false NOT NULL,
	social_security bool DEFAULT false NOT NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE hrms.tax_bracket (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	bracket_name varchar(100) NOT NULL,
	income_from numeric(15, 2) NOT NULL,
	income_to numeric(15, 2) NULL,
	tax_rate numeric(5, 2) NOT NULL CHECK (tax_rate >= 0 AND tax_rate <= 100),
	base_tax_amount numeric(15, 2) DEFAULT 0 NOT NULL,
	effective_from date NOT NULL,
	effective_to date NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
	CHECK (income_to IS NULL OR income_to > income_from),
	CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE TABLE hrms.social_security_rate (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	rate_name varchar(100) NOT NULL,
	employee_rate numeric(5, 2) NOT NULL CHECK (employee_rate >= 0 AND employee_rate <= 100),
	employer_rate numeric(5, 2) NOT NULL CHECK (employer_rate >= 0 AND employer_rate <= 100),
	min_wage_base numeric(15, 2) DEFAULT 0 NOT NULL,
	max_wage_base numeric(15, 2) NOT NULL,
	effective_from date NOT NULL,
	effective_to date NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
	CHECK (max_wage_base >= min_wage_base),
	CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE TABLE hrms.employee_loan (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	loan_type varchar(50) NOT NULL,
	principal_amount numeric(15, 2) NOT NULL CHECK (principal_amount >= 0),
	installment_amount numeric(15, 2) NOT NULL CHECK (installment_amount >= 0),
	start_date date NOT NULL,
	end_date date NULL,
	status varchar(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'PAID', 'CANCELLED')),
	CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE hrms.payroll_period (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"year" int4 NOT NULL,
	"month" int4 NOT NULL CHECK (month >= 1 AND month <= 12),
	start_date date NOT NULL,
	end_date date NOT NULL,
	payment_date date NULL,
	status varchar(30) DEFAULT 'DRAFT' NOT NULL CHECK (status IN ('DRAFT', 'CALCULATING', 'REVIEW', 'APPROVED', 'PAID', 'CLOSED', 'CANCELLED')),
	closed_at timestamptz NULL,
	closed_by_employee_id int8 NULL REFERENCES hrms.employee(id),
	approval_instance_id int8 NULL REFERENCES hrms.approval_instance(id),
	pre_approval_status varchar(30) NULL,
	UNIQUE (year, month),
	CHECK (end_date >= start_date)
);

CREATE TABLE hrms.payroll (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	period_id int8 NOT NULL REFERENCES hrms.payroll_period(id),
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	gross_income numeric(15, 2) DEFAULT 0 NOT NULL,
	total_deduction numeric(15, 2) DEFAULT 0 NOT NULL,
	net_salary numeric(15, 2) DEFAULT 0 NOT NULL,
	status varchar(30) DEFAULT 'DRAFT' NOT NULL CHECK (status IN ('DRAFT', 'CALCULATED', 'REVIEW', 'APPROVED', 'PAID', 'CANCELLED')),
	snapshot_employee_name varchar(300) NULL,
	snapshot_department_name varchar(255) NULL,
	snapshot_position_name varchar(255) NULL,
	snapshot_wage_type varchar(20) NULL,
	UNIQUE (period_id, employee_id)
);

CREATE TABLE hrms.payroll_detail (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	payroll_id int8 NOT NULL REFERENCES hrms.payroll(id) ON DELETE CASCADE,
	item_id int8 NOT NULL REFERENCES hrms.payroll_item(id),
	quantity numeric(12, 4) NULL,
	rate numeric(15, 4) NULL,
	amount numeric(15, 2) NOT NULL,
	calculation_source jsonb NULL
);

CREATE TABLE hrms.loan_installment (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	loan_id int8 NOT NULL REFERENCES hrms.employee_loan(id) ON DELETE CASCADE,
	installment_no int4 NOT NULL,
	due_date date NOT NULL,
	amount numeric(15, 2) NOT NULL CHECK (amount >= 0),
	paid_amount numeric(15, 2) DEFAULT 0 NOT NULL CHECK (paid_amount >= 0),
	status varchar(20) DEFAULT 'UNPAID' NOT NULL CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID', 'WAIVED')),
	payroll_detail_id int8 NULL REFERENCES hrms.payroll_detail(id),
	UNIQUE (loan_id, installment_no)
);

CREATE TABLE hrms.payroll_payment (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	period_id int8 NOT NULL REFERENCES hrms.payroll_period(id),
	company_bank_account_id int8 NOT NULL REFERENCES hrms.company_bank_account(id),
	transfer_date date NULL,
	status varchar(30) DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING', 'EXPORTED', 'TRANSFERRED', 'FAILED'))
);

CREATE TABLE hrms.payroll_payment_detail (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	payment_id int8 NOT NULL REFERENCES hrms.payroll_payment(id) ON DELETE CASCADE,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	bank_account_id int8 NOT NULL REFERENCES hrms.employee_bank_account(id),
	amount numeric(15, 2) NOT NULL CHECK (amount >= 0)
);

CREATE TABLE hrms.payslip (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	payroll_id int8 NOT NULL UNIQUE REFERENCES hrms.payroll(id),
	file_hash varchar(255) NULL,
	pdf_data bytea NULL,
	generated_at timestamptz DEFAULT now() NOT NULL
);

-- Requests, Announcements & Reporting
CREATE TABLE hrms.certificate_request (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	certificate_type_id int8 NOT NULL REFERENCES hrms.certificate_type(id),
	purpose text NULL,
	status varchar(30) DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'ISSUED', 'CANCELLED')),
	requested_at timestamptz DEFAULT now() NOT NULL,
	issued_file_url text NULL,
	issued_at timestamptz NULL,
	approval_instance_id int8 NULL REFERENCES hrms.approval_instance(id)
);

CREATE TABLE hrms.resignation_request (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	request_no varchar(50) NOT NULL UNIQUE,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	requested_last_working_date date NOT NULL,
	reason text NULL,
	status varchar(30) DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
	submitted_at timestamptz DEFAULT now() NOT NULL,
	cancelled_at timestamptz NULL,
	cancel_reason text NULL,
	resulting_contract_id int8 NULL REFERENCES hrms.employment_contract(id),
	approved_by_employee_id int8 NULL REFERENCES hrms.employee(id),
	approved_at timestamptz NULL
);

CREATE TABLE hrms.announcement (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title varchar(255) NOT NULL,
	"content" text NOT NULL,
	published_at timestamptz NULL,
	expire_at timestamptz NULL,
	created_by_employee_id int8 NULL REFERENCES hrms.employee(id),
	status varchar(20) DEFAULT 'DRAFT' NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED', 'EXPIRED', 'CANCELLED'))
);

CREATE TABLE hrms.announcement_target (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	announcement_id int8 NOT NULL REFERENCES hrms.announcement(id) ON DELETE CASCADE,
	target_type varchar(30) NOT NULL CHECK (target_type IN ('ALL', 'DIVISION', 'DEPARTMENT', 'ROLE', 'EMPLOYEE')),
	target_id int8 NULL
);

CREATE TABLE hrms.announcement_read (
	announcement_id int8 NOT NULL REFERENCES hrms.announcement(id) ON DELETE CASCADE,
	employee_id int8 NOT NULL REFERENCES hrms.employee(id),
	read_at timestamptz DEFAULT now() NOT NULL,
	PRIMARY KEY (announcement_id, employee_id)
);

CREATE TABLE hrms.notification (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id int8 NOT NULL REFERENCES hrms.user_account(id) ON DELETE CASCADE,
	notification_type varchar(50) NOT NULL,
	title varchar(255) NOT NULL,
	message text NULL,
	reference_type varchar(50) NULL,
	reference_id int8 NULL,
	is_read bool DEFAULT false NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	read_at timestamptz NULL
);

CREATE TABLE hrms.report_department_headcount_daily (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	department_id int8 NOT NULL REFERENCES hrms.department(id),
	snapshot_date date NOT NULL,
	headcount int4 DEFAULT 0 NOT NULL CHECK (headcount >= 0),
	UNIQUE (department_id, snapshot_date)
);

CREATE TABLE hrms.report_turnover_monthly (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	department_id int8 NOT NULL REFERENCES hrms.department(id),
	"year" int4 NOT NULL,
	"month" int4 NOT NULL CHECK (month >= 1 AND month <= 12),
	joined_count int4 DEFAULT 0 NOT NULL CHECK (joined_count >= 0),
	resigned_count int4 DEFAULT 0 NOT NULL CHECK (resigned_count >= 0),
	turnover_rate numeric(5, 2) DEFAULT 0.00 NOT NULL,
	UNIQUE (department_id, year, month)
);

CREATE TABLE hrms.audit_log (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id int8 NULL REFERENCES hrms.user_account(id),
	"action" varchar(30) NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'APPROVE', 'REJECT', 'EXPORT')),
	entity_type varchar(100) NOT NULL,
	entity_id int8 NULL,
	field_name varchar(100) NULL,
	old_value jsonb NULL,
	new_value jsonb NULL,
	ip_address inet NULL,
	user_agent text NULL,
	created_at timestamptz DEFAULT now() NOT NULL
);
