-- ==============================================================================
-- แฟ้มเอกสารพนักงาน (hrms.employee_document)
-- ตารางมีอยู่แล้ว — สคริปต์นี้เพิ่มคอลัมน์ที่ระบบใช้ (ชนิดไฟล์ ขนาด หมายเหตุ คำขอต้นทาง)
-- รันซ้ำได้ปลอดภัย (idempotent)
-- ควรรัน general_request.sql ก่อน
-- ==============================================================================
BEGIN;

CREATE TABLE IF NOT EXISTS hrms.employee_document (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id             bigint       NOT NULL REFERENCES hrms.employee(id) ON DELETE CASCADE,
    document_type_id        bigint       NOT NULL REFERENCES hrms.document_type(id),
    file_name               varchar(255) NULL,
    file_data               bytea        NULL,
    issued_date             date         NULL,
    expiry_date             date         NULL,
    uploaded_at             timestamptz  NOT NULL DEFAULT now(),
    uploaded_by_employee_id bigint       NULL REFERENCES hrms.employee(id),
    CHECK (expiry_date IS NULL OR issued_date IS NULL OR expiry_date >= issued_date)
);

ALTER TABLE hrms.employee_document ADD COLUMN IF NOT EXISTS file_mime_type varchar(100) NULL;
ALTER TABLE hrms.employee_document ADD COLUMN IF NOT EXISTS file_size bigint NULL;
ALTER TABLE hrms.employee_document ADD COLUMN IF NOT EXISTS remarks text NULL;
ALTER TABLE hrms.employee_document ADD COLUMN IF NOT EXISTS source_general_request_id bigint NULL;

-- ผูกกับคำขอเอกสารทั่วไปต้นทาง (ถ้ามีตาราง general_request แล้ว)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables
               WHERE table_schema = 'hrms' AND table_name = 'general_request')
       AND NOT EXISTS (SELECT 1 FROM pg_constraint
               WHERE conname = 'employee_document_source_general_request_fkey') THEN
        ALTER TABLE hrms.employee_document
            ADD CONSTRAINT employee_document_source_general_request_fkey
            FOREIGN KEY (source_general_request_id) REFERENCES hrms.general_request(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_employee_document_employee ON hrms.employee_document (employee_id);
CREATE INDEX IF NOT EXISTS ix_employee_document_expiry ON hrms.employee_document (expiry_date);
-- คำขอหนึ่งรายการคัดลอกเข้าแฟ้มได้ครั้งเดียว
CREATE UNIQUE INDEX IF NOT EXISTS ux_employee_document_source_request
    ON hrms.employee_document (source_general_request_id)
    WHERE source_general_request_id IS NOT NULL;

COMMIT;
