-- ==============================================================================
-- คำขออื่นๆ (General Requests) — คำขอทั่วไปถึงฝ่ายบุคคลที่ผ่านสายการอนุมัติ
-- ประเภทเอกสารในสายการอนุมัติ: GENERAL_REQUEST
-- รันซ้ำได้ปลอดภัย (idempotent)
-- ==============================================================================
BEGIN;

CREATE TABLE IF NOT EXISTS hrms.general_request (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no           varchar(30)  NOT NULL DEFAULT '',
    employee_id          bigint       NOT NULL REFERENCES hrms.employee(id) ON DELETE CASCADE,
    request_type         varchar(150) NOT NULL,
    purpose              text         NOT NULL,
    notes                text         NULL,
    issue_date           date         NULL,
    expiry_date          date         NULL,
    file_name            varchar(255) NULL,
    file_mime_type       varchar(100) NULL,
    file_size            bigint       NULL,
    file_data            bytea        NULL,
    status               varchar(30)  NOT NULL DEFAULT 'PENDING',
    reject_reason        text         NULL,
    requested_at         timestamptz  NOT NULL DEFAULT now(),
    completed_at         timestamptz  NULL,
    approval_instance_id bigint       NULL REFERENCES hrms.approval_instance(id) ON DELETE SET NULL,
    CONSTRAINT general_request_status_check
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS ix_general_request_employee ON hrms.general_request (employee_id);
CREATE INDEX IF NOT EXISTS ix_general_request_instance ON hrms.general_request (approval_instance_id);

COMMIT;

-- เพิ่มค่าใน enum ประเภทเอกสาร (คอลัมน์ document_type ใช้ varchar อยู่แล้ว แต่เพิ่มไว้ให้ตรงกัน)
-- ALTER TYPE ... ADD VALUE ต้องรันนอก transaction
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
               WHERE n.nspname = 'hrms' AND t.typname = 'approval_document_type_enum') THEN
        ALTER TYPE hrms.approval_document_type_enum ADD VALUE IF NOT EXISTS 'GENERAL_REQUEST';
    END IF;
END $$;
