-- ปิดยอดวันลาสิ้นปี (ปีละครั้ง) — ใช้กับ LeaveYearEndService
-- รันซ้ำได้ (IF NOT EXISTS)
CREATE TABLE IF NOT EXISTS hrms.leave_year_closing (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year                   INT NOT NULL,
    closed_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_by_employee_id  BIGINT NULL REFERENCES hrms.employee(id) ON DELETE SET NULL,
    balance_count          INT NOT NULL DEFAULT 0,
    total_carried_days     NUMERIC(10,2) NOT NULL DEFAULT 0,
    total_forfeited_days   NUMERIC(10,2) NOT NULL DEFAULT 0,
    note                   TEXT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_leave_year_closing_year ON hrms.leave_year_closing (year);

-- ใช้หายอดยกมาที่ถึงวันหมดอายุ (งานเบื้องหลัง)
CREATE INDEX IF NOT EXISTS ix_leave_balance_carry_expiry ON hrms.leave_balance (carry_forward_expiry)
    WHERE carry_forward_expiry IS NOT NULL;
