export interface NationalityOption {
  id: number;
  name: string;
}

export const NATIONALITIES: NationalityOption[] = [
  { id: 1, name: "ไทย (Thai)" },
  { id: 2, name: "ญี่ปุ่น (Japanese)" },
  { id: 3, name: "สิงคโปร์ (Singaporean)" },
  { id: 4, name: "อเมริกัน (American)" },
  { id: 5, name: "ลาว (Laotian)" },
  { id: 6, name: "เมียนมา (Burmese)" },
  { id: 7, name: "กัมพูชา (Cambodian)" },
  { id: 8, name: "เวียดนาม (Vietnamese)" },
  { id: 9, name: "มาเลเซีย (Malaysian)" },
  { id: 10, name: "อินโดนีเซีย (Indonesian)" },
  { id: 11, name: "ฟิลิปปินส์ (Filipino)" },
  { id: 12, name: "บรูไน (Bruneian)" },
  { id: 13, name: "ติมอร์-เลสเต (Timorese)" },
  { id: 14, name: "จีน (Chinese)" },
  { id: 15, name: "เกาหลีใต้ (South Korean)" },
  { id: 16, name: "เกาหลีเหนือ (North Korean)" },
  { id: 17, name: "ไต้หวัน (Taiwanese)" },
  { id: 18, name: "ฮ่องกง (Hong Konger)" },
  { id: 19, name: "มาเก๊า (Macanese)" },
  { id: 20, name: "มองโกเลีย (Mongolian)" },
  { id: 21, name: "อินเดีย (Indian)" },
  { id: 22, name: "ปากีสถาน (Pakistani)" },
  { id: 23, name: "บังกลาเทศ (Bangladeshi)" },
  { id: 24, name: "ศรีลังกา (Sri Lankan)" },
  { id: 25, name: "เนปาล (Nepalese)" },
  { id: 26, name: "ภูฏาน (Bhutanese)" },
  { id: 27, name: "มัลดีฟส์ (Maldivian)" },
  { id: 28, name: "อัฟกานิสถาน (Afghan)" },
  { id: 29, name: "คาซัคสถาน (Kazakhstani)" },
  { id: 30, name: "อุซเบกิสถาน (Uzbek)" },
  { id: 31, name: "เติร์กเมนิสถาน (Turkmen)" },
  { id: 32, name: "คีร์กีซสถาน (Kyrgyzstani)" },
  { id: 33, name: "ทาจิกิสถาน (Tajik)" },
  { id: 34, name: "สหรัฐอาหรับเอมิเรตส์ (Emirati)" },
  { id: 35, name: "ซาอุดีอาระเบีย (Saudi)" },
  { id: 36, name: "คูเวต (Kuwaiti)" },
  { id: 37, name: "กาตาร์ (Qatari)" },
  { id: 38, name: "บาห์เรน (Bahraini)" },
  { id: 39, name: "โอมาน (Omani)" },
  { id: 40, name: "เยเมน (Yemeni)" },
  { id: 41, name: "อิสราเอล (Israeli)" },
  { id: 42, name: "จอร์แดน (Jordanian)" },
  { id: 43, name: "เลบานอน (Lebanese)" },
  { id: 44, name: "ซีเรีย (Syrian)" },
  { id: 45, name: "อิรัก (Iraqi)" },
  { id: 46, name: "อิหร่าน (Iranian)" },
  { id: 47, name: "ตุรกี (Turkish)" },
  { id: 48, name: "ไซปรัส (Cypriot)" },
  { id: 49, name: "ปาเลสไตน์ (Palestinian)" },
  { id: 50, name: "บริติช / สหราชอาณาจักร (British)" },
  { id: 51, name: "อังกฤษ (English)" },
  { id: 52, name: "สกอตแลนด์ (Scottish)" },
  { id: 53, name: "เวลส์ (Welsh)" },
  { id: 54, name: "ไอร์แลนด์เหนือ (Northern Irish)" },
  { id: 55, name: "ไอร์แลนด์ (Irish)" },
  { id: 56, name: "ฝรั่งเศส (French)" },
  { id: 57, name: "เยอรมัน (German)" },
  { id: 58, name: "สวิส (Swiss)" },
  { id: 59, name: "เนเธอร์แลนด์ (Dutch)" },
  { id: 60, name: "เบลเยียม (Belgian)" },
  { id: 61, name: "ลักเซมเบิร์ก (Luxembourgish)" },
  { id: 62, name: "โมนาโก (Monegasque)" },
  { id: 63, name: "สวีเดน (Swedish)" },
  { id: 64, name: "นอร์เวย์ (Norwegian)" },
  { id: 65, name: "เดนมาร์ก (Danish)" },
  { id: 66, name: "ฟินแลนด์ (Finnish)" },
  { id: 67, name: "ไอซ์แลนด์ (Icelandic)" },
  { id: 68, name: "อิตาลี (Italian)" },
  { id: 69, name: "สเปน (Spanish)" },
  { id: 70, name: "โปรตุเกส (Portuguese)" },
  { id: 71, name: "กรีซ (Greek)" },
  { id: 72, name: "มอลตา (Maltese)" },
  { id: 73, name: "อันดอร์รา (Andorran)" },
  { id: 74, name: "ซานมารีโน (Sammarinese)" },
  { id: 75, name: "วาติกัน (Vatican)" },
  { id: 76, name: "ออสเตรีย (Austrian)" },
  { id: 77, name: "โปแลนด์ (Polish)" },
  { id: 78, name: "เช็ก (Czech)" },
  { id: 79, name: "สโลวาเกีย (Slovak)" },
  { id: 80, name: "ฮังการี (Hungarian)" },
  { id: 81, name: "โรมาเนีย (Romanian)" },
  { id: 82, name: "บัลแกเรีย (Bulgarian)" },
  { id: 83, name: "รัสเซีย (Russian)" },
  { id: 84, name: "ยูเครน (Ukrainian)" },
  { id: 85, name: "เบลารุส (Belarusian)" },
  { id: 86, name: "เอสโตเนีย (Estonian)" },
  { id: 87, name: "ลัตเวีย (Latvian)" },
  { id: 88, name: "ลิทัวเนีย (Lithuanian)" },
  { id: 89, name: "มอลโดวา (Moldovan)" },
  { id: 90, name: "จอร์เจีย (Georgian)" },
  { id: 91, name: "อาร์มีเนีย (Armenian)" },
  { id: 92, name: "อาเซอร์ไบจาน (Azerbaijani)" },
  { id: 93, name: "โครเอเชีย (Croatian)" },
  { id: 94, name: "เซอร์เบีย (Serbian)" },
  { id: 95, name: "สโลวีเนีย (Slovenian)" },
  { id: 96, name: "บอสเนียและเฮอร์เซโกวีนา (Bosnian)" },
  { id: 97, name: "มาซิโดเนียเหนือ (Macedonian)" },
  { id: 98, name: "มอนเตเนโกร (Montenegrin)" },
  { id: 99, name: "แอลเบเนีย (Albanian)" },
  { id: 100, name: "คอซอวอ (Kosovar)" },
  { id: 101, name: "แคนาดา (Canadian)" },
  { id: 102, name: "เม็กซิโก (Mexican)" },
  { id: 103, name: "กัวเตมาลา (Guatemalan)" },
  { id: 104, name: "เบลีซ (Belizean)" },
  { id: 105, name: "ฮอนดูรัส (Honduran)" },
  { id: 106, name: "เอลซัลวาดอร์ (Salvadoran)" },
  { id: 107, name: "นิการากัว (Nicaraguan)" },
  { id: 108, name: "คอสตาริกา (Costa Rican)" },
  { id: 109, name: "ปานามา (Panamanian)" },
  { id: 110, name: "คิวบา (Cuban)" },
  { id: 111, name: "จาเมกา (Jamaican)" },
  { id: 112, name: "เฮติ (Haitian)" },
  { id: 113, name: "โดมินิกัน (Dominican)" },
  { id: 114, name: "บาฮามาส (Bahamian)" },
  { id: 115, name: "บาร์เบโดส (Barbadian)" },
  { id: 116, name: "ตรินิแดดและโตเบโก (Trinidadian)" },
  { id: 117, name: "แอนติกาและบาร์บูดา (Antiguan)" },
  { id: 118, name: "เซนต์ลูเซีย (Saint Lucian)" },
  { id: 119, name: "เซนต์วินเซนต์และเกรนาดีนส์ (Vincentian)" },
  { id: 120, name: "เกรเนดา (Grenadian)" },
  { id: 121, name: "เซนต์คิตส์และเนวิส (Kittitian)" },
  { id: 122, name: "บราซิล (Brazilian)" },
  { id: 123, name: "อาร์เจนตินา (Argentine)" },
  { id: 124, name: "ชิลี (Chilean)" },
  { id: 125, name: "โคลอมเบีย (Colombian)" },
  { id: 126, name: "เปรู (Peruvian)" },
  { id: 127, name: "เวเนซุเอลา (Venezuelan)" },
  { id: 128, name: "เอกวาดอร์ (Ecuadorian)" },
  { id: 129, name: "โบลิเวีย (Bolivian)" },
  { id: 130, name: "ปารากวัย (Paraguayan)" },
  { id: 131, name: "อุรุกวัย (Uruguayan)" },
  { id: 132, name: "กายอานา (Guyanese)" },
  { id: 133, name: "ซูรินาม (Surinamese)" },
  { id: 134, name: "อียิปต์ (Egyptian)" },
  { id: 135, name: "โมร็อกโก (Moroccan)" },
  { id: 136, name: "แอลจีเรีย (Algerian)" },
  { id: 137, name: "ตูนิเซีย (Tunisian)" },
  { id: 138, name: "ลิเบีย (Libyan)" },
  { id: 139, name: "ซูดาน (Sudanese)" },
  { id: 140, name: "ซูดานใต้ (South Sudanese)" },
  { id: 141, name: "เอธิโอเปีย (Ethiopian)" },
  { id: 142, name: "เคนยา (Kenyan)" },
  { id: 143, name: "แทนซาเนีย (Tanzanian)" },
  { id: 144, name: "ยูกันดา (Ugandan)" },
  { id: 145, name: "รวันดา (Rwandan)" },
  { id: 146, name: "บุรุนดี (Burundian)" },
  { id: 147, name: "โซมาเลีย (Somali)" },
  { id: 148, name: "จิบูตี (Djiboutian)" },
  { id: 149, name: "เอริเทรีย (Eritrean)" },
  { id: 150, name: "เซเชลส์ (Seychellois)" },
  { id: 151, name: "คอโมโรส (Comorian)" },
  { id: 152, name: "มอริเชียส (Mauritian)" },
  { id: 153, name: "มาดากัสการ์ (Malagasy)" },
  { id: 154, name: "ไนจีเรีย (Nigerian)" },
  { id: 155, name: "กานา (Ghanaian)" },
  { id: 156, name: "แคเมอรูน (Cameroonian)" },
  { id: 157, name: "ไอวอรีโคสต์ (Ivorian)" },
  { id: 158, name: "เซเนกัล (Senegalese)" },
  { id: 159, name: "มาลี (Malian)" },
  { id: 160, name: "กินี (Guinean)" },
  { id: 161, name: "เบนิน (Beninese)" },
  { id: 162, name: "โตโก (Togolese)" },
  { id: 163, name: "บูร์กินาฟาโซ (Burkinabe)" },
  { id: 164, name: "ไนเจอร์ (Nigerien)" },
  { id: 165, name: "ชาด (Chadian)" },
  { id: 166, name: "มอริเตเนีย (Mauritanian)" },
  { id: 167, name: "เซียร์ราลีโอน (Sierra Leonean)" },
  { id: 168, name: "ไลบีเรีย (Liberian)" },
  { id: 169, name: "แกมเบีย (Gambian)" },
  { id: 170, name: "กินี-บิสเซา (Bissau-Guinean)" },
  { id: 171, name: "เคปเวิร์ด (Cape Verdean)" },
  { id: 172, name: "กาบอง (Gabonese)" },
  { id: 173, name: "คองโก (Congolese)" },
  { id: 174, name: "ดีอาร์ คองโก (DR Congolese)" },
  { id: 175, name: "อิเควทอเรียลกินี (Equatorial Guinean)" },
  { id: 176, name: "สาธารณรัฐแอฟริกากลาง (Central African)" },
  { id: 177, name: "เซาตูเมและปรินซิปี (Sao Tomean)" },
  { id: 178, name: "แอฟริกาใต้ (South African)" },
  { id: 179, name: "ซิมบับเว (Zimbabwean)" },
  { id: 180, name: "แซมเบีย (Zambian)" },
  { id: 181, name: "บอตสวานา (Motswana)" },
  { id: 182, name: "นามิเบีย (Namibian)" },
  { id: 183, name: "แองโกลา (Angolan)" },
  { id: 184, name: "โมซัมบิก (Mozambican)" },
  { id: 185, name: "มาลาวี (Malawian)" },
  { id: 186, name: "เลโซโท (Basotho)" },
  { id: 187, name: "เอสวาตินี (Swazi)" },
  { id: 188, name: "ออสเตรเลีย (Australian)" },
  { id: 189, name: "นิวซีแลนด์ (New Zealander)" },
  { id: 190, name: "ฟิจิ (Fijian)" },
  { id: 191, name: "ปาปัวนิวกินี (Papua New Guinean)" },
  { id: 192, name: "ซามัว (Samoan)" },
  { id: 193, name: "ตองงา (Tongan)" },
  { id: 194, name: "วานูอาตู (Ni-Vanuatu)" },
  { id: 195, name: "หมู่เกาะโซโลมอน (Solomon Islander)" },
  { id: 196, name: "ไมโครนีเซีย (Micronesian)" },
  { id: 197, name: "ปาเลา (Palauan)" },
  { id: 198, name: "หมู่เกาะมาร์แชลล์ (Marshallese)" },
  { id: 199, name: "คิริบาส (I-Kiribati)" },
  { id: 200, name: "นาอูรู (Nauruan)" },
  { id: 201, name: "ตูวาลู (Tuvaluan)" },
  { id: 202, name: "ไร้สัญชาติ (Stateless)" },
  { id: 203, name: "อื่นๆ (Other)" },
];
